version: '3.8'

services:
  postgres:
    container_name: werkze_db
    image: 'postgres:latest'
    env_file: ../../.env
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
      - postgres-staging:/var/lib/postgresql/data
  backend:
    container_name: werkze_backend
    env_file: ../../.env
    build:
      context: ${BACKEND_ROOT}
      dockerfile: ./Dockerfile
    command: yarn start:prod
    tty: true
    ports:
      - '3000:3000'
  frontend:
    container_name: werkze_frontend
    env_file: ../../.env
    build:
      context: ${FRONTEND_ROOT}
      dockerfile: ./Dockerfile
    environment:
      - HOST=0.0.0.0
    command: serve -s build
    tty: true
    ports:
      - '3001:3000'

volumes:
  postgres-staging:
